LINK_TARGET=sdlwin.exe

OBJS =  \
    sdl_window.o \

INCLUDEPATHS = \
    -I/usr/local/include \
    -I/usr/local/include/SDL2

LIBPATHS = \
     -L/usr/local/lib \
     -L/opt/local/lib

LIBS = \
      -lSDL2

 REBUILDABLES = $(OBJS) $(LINK_TARGET)

all : $(LINK_TARGET)
	echo all done

clean :
	rm $(LINK_TARGET)
    
$(LINK_TARGET) : $(OBJS)
	gcc \
    $(LIBPATHS) \
    $(LIBS) \
    -v -g -o $@ $^ 


%.o : %.c
	gcc -g -o $@ \
    $(INCLUDEPATHS) \
    -c -v $<